CREATE SEQUENCE SEQ_USERS_NO
  NOCACHE
/

CREATE SEQUENCE SEQ_CATEGORY_NO
  NOCACHE
/

CREATE SEQUENCE SEQ_POST_NO
  NOCACHE
/

CREATE SEQUENCE SEQ_COMMENTS_NO
  NOCACHE
/

CREATE TABLE USERS
(
  USERNO   NUMBER        NOT NULL
    PRIMARY KEY,
  ID       VARCHAR2(50)  NOT NULL
    UNIQUE,
  USERNAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(50)  NOT NULL,
  JOINDATE DATE          NOT NULL
)
/

CREATE TABLE BLOG
(
  ID        VARCHAR2(50)  NOT NULL
    PRIMARY KEY
    CONSTRAINT SYS_C005258
    REFERENCES USERS (ID),
  BLOGTITLE VARCHAR2(200) NOT NULL,
  LOGOFILE  VARCHAR2(400) DEFAULT NULL
)
/

CREATE TABLE CATEGORY
(
  CATENO      NUMBER        NOT NULL
    PRIMARY KEY,
  ID          VARCHAR2(50)  NOT NULL
    REFERENCES BLOG,
  CATENAME    VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  REGDATE     DATE          NOT NULL
)
/

CREATE TABLE POST
(
  POSTNO      NUMBER        NOT NULL
    PRIMARY KEY,
  CATENO      NUMBER        NOT NULL
    REFERENCES CATEGORY,
  POSTTITLE   VARCHAR2(300) NOT NULL,
  POSTCONTENT VARCHAR2(4000),
  REGDATE     DATE          NOT NULL
)
/

CREATE TABLE COMMENTS
(
  CMTNO      NUMBER         NOT NULL
    PRIMARY KEY,
  POSTNO     NUMBER         NOT NULL
    REFERENCES POST,
  USERNO     NUMBER         NOT NULL
    REFERENCES USERS,
  CMTCONTENT VARCHAR2(1000) NOT NULL,
  REGDATE    DATE           NOT NULL
)
/


